// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzf-nCSSoJy-jqjBLAG19hXV4Z_-GiVYw',
    appId: '1:1057275353571:web:b12168871eb9cffc31a8d6',
    messagingSenderId: '1057275353571',
    projectId: 'fir-authn-7daf3',
    authDomain: 'fir-authn-7daf3.firebaseapp.com',
    storageBucket: 'fir-authn-7daf3.appspot.com',
    measurementId: 'G-5VR8H8XSCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBWx8TpqpfuI6J69KUrZje7M2In50tUg',
    appId: '1:1057275353571:android:b3699a4ab028b36431a8d6',
    messagingSenderId: '1057275353571',
    projectId: 'fir-authn-7daf3',
    storageBucket: 'fir-authn-7daf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0bI_pBbRAHFBIEtJazc_sU5ry32ld0Y',
    appId: '1:1057275353571:ios:2299c2a0eed280f031a8d6',
    messagingSenderId: '1057275353571',
    projectId: 'fir-authn-7daf3',
    storageBucket: 'fir-authn-7daf3.appspot.com',
    iosBundleId: 'com.example.firebaseAuthn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0bI_pBbRAHFBIEtJazc_sU5ry32ld0Y',
    appId: '1:1057275353571:ios:2299c2a0eed280f031a8d6',
    messagingSenderId: '1057275353571',
    projectId: 'fir-authn-7daf3',
    storageBucket: 'fir-authn-7daf3.appspot.com',
    iosBundleId: 'com.example.firebaseAuthn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzf-nCSSoJy-jqjBLAG19hXV4Z_-GiVYw',
    appId: '1:1057275353571:web:e9a694477ed021fa31a8d6',
    messagingSenderId: '1057275353571',
    projectId: 'fir-authn-7daf3',
    authDomain: 'fir-authn-7daf3.firebaseapp.com',
    storageBucket: 'fir-authn-7daf3.appspot.com',
    measurementId: 'G-7VGH1935P4',
  );
}
